### PR TITLE
fix: provide tracerProvider and meterProvider explicitly 

### LINKED ISSUE #216: exports do not reach Cloud Logging if app also bound to Dynatrace
since 1.0.0

currently unclear what causes this issue...

### PR DESCRIPTION
**Pull request by sjvans**
closes #216

### CODE REVIEW

File: lib/tracing/index.js [hunk 1]
```diff
@@ -148,10 +148,12 @@ module.exports = resource => {
   })
 
   /*
-   * add CAP instrumentations
+   * add CAP tracing
```
Comment (sjvans) [inline lib/tracing/index.js:151]:
```suggestion
   * add tracing
```
